### ISSUE TITLE
Links to the Connector repositories still pointing to the old, archived repos

### ISSUE THREAD

**Issue by christian-konrad** [camunda-community-hub/camunda-8-connectors#15]
The [links to the Connector repositories](https://github.com/camunda-community-hub/camunda-8-connectors#out-of-the-box-connectors) still pointing to the old, archived repos, instead of the connector-bundle repo.

**Comment by chillleader** [comment]
Thank you for reporting this!

As of now, the links have been [updated](https://github.com/camunda-community-hub/camunda-8-connectors/commit/cc9febc9c6b8c44ce357481c05a61dfcf8e9f7b0), so I'm closing this issue.
