### ISSUE TITLE
Add new connector to the Partner Connectors - Connector runtimes provided by Camunda partners:

### ISSUE THREAD

**Issue by chandra-chavan** [camunda-community-hub/camunda-8-connectors#23]
Hello, Team!

I am Chandra Chavan from Infosys ltd. Can you pls help to add MS SQL - connector Under "Partner Connectors - Connector runtimes provided by Camunda partners:". 

Connector | Partner | JAR with   dependencies | Code repository | Documentation | License
-- | -- | -- | -- | -- | --
MSSQL | Infosys |   | Github | Documentation | MIT

Thanks & regards,
Chandra Chavan.

**Comment by chillleader** [comment]
Done in https://github.com/camunda-community-hub/camunda-8-connectors/pull/24
