### ISSUE TITLE
Camunda Carbon Reductor

### ISSUE THREAD

**Issue by hehnle** [camunda-community-hub/camunda-8-connectors#25]
Hello, Team!

I am Philipp Hehnle from the envite consulting GmbH. We are happy to introduce our Camunda Carbon Reductor connector and think it will contribute to the community.

## About the Connector

The Camunda Carbon Reductor can be configured to reduce carbon emissions based on Service Level Agreements (SLA) for the process like the maximum cycle time for a process instance. Information about the SLA is entered along with a forecast of how long the remaining tasks will take. The configuration allows the Carbon Reductor to independently optimize execution by time shifting the remaining activities without violating the SLA for maximum cycle time. When called our Camunda Carbon Reductor Job Worker picks up the job and uses the configuration to query the carbon-aware-sdk for a forecast of the carbon intensity of the current location to find the optimal time window for the process to proceed.

## Checklist

- [X] I have added a license file (and terms of use where applicable): https://github.com/envite-consulting/camunda-carbon-reductor/blob/main/LICENSE
- [X] The Readme file contains summary: https://github.com/envite-consulting/camunda-carbon-reductor/blob/main/camunda-carbon-reductor-c8/README.md
- [X] Documentation describes how to use the connector: https://github.com/envite-consulting/camunda-carbon-reductor/blob/main/camunda-carbon-reductor-c8/README.md
- [X] Documentation describes how to install the connector: https://github.com/envite-consulting/camunda-carbon-reductor/blob/main/camunda-carbon-reductor-c8/README.md
- [X] Documentation describes how to contact maintainer: https://github.com/envite-consulting/camunda-carbon-reductor

Thank you!

**Comment by xomiamoore** [comment]
Added! Thank you for your submission, @hehnle!
