### ISSUE TITLE
Incentro is presenting the Alfresco connector

### ISSUE THREAD

**Issue by maartenincentro** [camunda-community-hub/camunda-8-connectors#28]
Hello, Team!

I am Maarten van Veelen from Incentro. We are happy to introduce our Alfresco connector and think it will contribute to the community.

## About the Connector

This connector makes it possible to interact with Alfresco Content Services, a leading Open Source Document Management System. The connector uses the REST Protocol connector as a base and is created just by configuring the element template. The initial version just has one operation: create a folder in Alfresco. Of course we will add more operations in the future.

## Checklist

- [x] I have added a license file (and terms of use where applicable): [<link>](https://github.com/incentro/camunda-connectors/blob/main/LICENSE)
- [x] The Readme file contains summary: <[link](https://github.com/incentro/camunda-connectors/blob/main/README.md)>
- [x] Documentation describes how to use the connector: <[link](https://github.com/incentro/camunda-connectors/blob/main/README.md)>
- [x] Documentation describes how to install the connector: <[link](https://github.com/incentro/camunda-connectors/blob/main/README.md)>
- [x] Documentation describes how to contact maintainer: <[link](https://github.com/incentro/camunda-connectors/blob/main/README.md)>

Thank you!

**Comment by maartenincentro** [comment]
@bastiankoerber hi Bastian. Can you have a look at the issue I created?

**Comment by bastiankoerber** [comment]
HI @maartenincentro,
thanks for your contribution. Would like to be part of the connector's awesome list?

**Comment by maartenincentro** [comment]
Hi @bastiankoerber yes I would love to be part of it!
