### ISSUE TITLE
Camunda Connector for MongoDB

### ISSUE THREAD

**Issue by antonyalex-acheron** [camunda-community-hub/camunda-8-connectors#43]
Hello, Team!

I am AntonyAlex from the Acheron Software Consultancy Pvt Ltd. We are happy to introduce our MongoDB connector and think it will contribute to the community.

## About the Connector

Connector to integrate to MongoDB, Provides operation to perform Create database/collection, Insert/Update/Delete documents in MongoDB. 

## Checklist

- [x] I have added a license file (and terms of use where applicable): https://github.com/Acheron-Camunda/mongodb-connector/blob/main/LICENSE
- [x] The Readme file contains summary: https://github.com/Acheron-Camunda/mongodb-connector/blob/main/README.md
- [x] Documentation describes how to use the connector: https://github.com/Acheron-Camunda/mongodb-connector/blob/main/README.md
- [x] Documentation describes how to install the connector: https://github.com/Acheron-Camunda/mongodb-connector/blob/main/README.md
- [x] Documentation describes how to contact maintainer: https://github.com/Acheron-Camunda/mongodb-connector/blob/main/README.md

Thank you!

**Comment by bastiankoerber** [comment]
done
