### ISSUE TITLE
Adding Email Watch Inbound Connector to the Awesome List

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/camunda-8-connectors#45]
Hello, Team!

I am Joe Pappas from Camunda. We are happy to introduce our Email Watch Inbound connector and think it will contribute to the community.

## About the Connector

We'll are asked whether emails can drive Camunda processes from time to time. Of course the answer has always been yes but this connector will make it easier to implement without having to develop the code yourself

## Checklist

- [ X] I have added a license file (and terms of use where applicable): <link>
- [ X] The Readme file contains summary: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-email-watch)
- [ X] Documentation describes how to use the connector: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-email-watch)
- [ X] Documentation describes how to install the connector: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-email-watch)
- [ ]X Documentation describes how to contact maintainer: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-email-watch)

Thank you!

**Comment by bastiankoerber** [comment]
done
