### ISSUE TITLE
Add File Watch Inbound Connector

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/camunda-8-connectors#47]
Hello, Team!

I am Joe Pappas from Camunda. We are happy to introduce our File Watch Inbound connector and think it will contribute to the community.

## About the Connector

An Inbound connector that does not require an additional technology to be installed. Might work as an Inbound Connector tutorial given its simplicity. Add, modify, and delete files in monitored directories to drive process flows

## Checklist

- [ X] I have added a license file (and terms of use where applicable): [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-file-watch)
- [ X] The Readme file contains summary: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-file-watch)
- [ X] Documentation describes how to use the connector: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-file-watch)
- [X ] Documentation describes how to install the connector: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-file-watch)
- [ X] Documentation describes how to contact maintainer: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-file-watch)

Thank you!

**Comment by bastiankoerber** [comment]
done
