### ISSUE TITLE
Add NATS outbound connector

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/camunda-8-connectors#48]
Hello, Team!

I am Joe Pappas from Camunda. We are happy to introduce our NATS Outbound connector and think it will contribute to the community.

## About the Connector

Similar to Kafka, NATS is an open source messaging system, dead simple to set up and use. Built based on feedback from someone current using NATS

## Checklist

- [X ] I have added a license file (and terms of use where applicable): [Here](https://github.com/camunda-community-hub/camunda-8-connector-nats)
- [ X] The Readme file contains summary: [Here](https://github.com/camunda-community-hub/camunda-8-connector-nats)
- [ X] Documentation describes how to use the connector: [Here](https://github.com/camunda-community-hub/camunda-8-connector-nats)
- [ X] Documentation describes how to install the connector: [Here](https://github.com/camunda-community-hub/camunda-8-connector-nats)
- [ X] Documentation describes how to contact maintainer: [Here](https://github.com/camunda-community-hub/camunda-8-connector-nats)

Thank you!

**Comment by bastiankoerber** [comment]
done
