### ISSUE TITLE
Add NATS Inbound Connector

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/camunda-8-connectors#49]
Hello, Team!

I am Joe Pappas from the Camunda. We are happy to introduce our NATS Inbound connector and think it will contribute to the community.

## About the Connector

Similar to NATS Outbound. Open source messaging similar to Kafka, dead simple to use.

## Checklist

- [X ] I have added a license file (and terms of use where applicable): [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-nats)
- [X ] The Readme file contains summary: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-nats)
- [X ] Documentation describes how to use the connector: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-nats)
- [X ] Documentation describes how to install the connector: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-nats)
- [ X] Documentation describes how to contact maintainer: [Here](https://github.com/camunda-community-hub/camunda-8-inbound-connector-nats)

Thank you!

**Comment by bastiankoerber** [comment]
done
