### ISSUE TITLE
Add open source UiPath connector

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/camunda-8-connectors#51]
Hello, Team!

I am Joe Pappas from the Camunda. We are happy to introduce our open source UiPath connector and think it will contribute to the community.

## About the Connector

Though I am concerned about confusion with Camunda's official connector, this is an open source alternative

## Checklist

- [ X] I have added a license file (and terms of use where applicable): [Here](https://github.com/camunda-community-hub/camunda-8-connector-uipath)
- [ X] The Readme file contains summary: [Here](https://github.com/camunda-community-hub/camunda-8-connector-uipath)
- [ X] Documentation describes how to use the connector: [Here](https://github.com/camunda-community-hub/camunda-8-connector-uipath)
- [ X] Documentation describes how to install the connector: [Here](https://github.com/camunda-community-hub/camunda-8-connector-uipath)
- [ X] Documentation describes how to contact maintainer: [Here](https://github.com/camunda-community-hub/camunda-8-connector-uipath)

Thank you!

**Comment by bastiankoerber** [comment]
https://github.com/camunda-community-hub/camunda-8-connectors/pull/54 will close the ticket
