### ISSUE TITLE
Add Inbound MongoDB Connector to the Awesome List

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/camunda-8-connectors#55]
Hello, Team!

I am Joe Pappas from Camunda. We are happy to introduce our Inbound MongoDB connector and think it will contribute to the community.

## About the Connector

The connector uses the Change Streams feature of MongoDB which acts like a messaging service to start processes or send messages as required. I was asked about MongoDB and Camunda during a public webinar which served as the inspiration to build one

## Checklist

- [ X] I have added a license file (and terms of use where applicable): <link>
- [ X] The Readme file contains summary: <link>
- [ X] Documentation describes how to use the connector: <link>
- [ X] Documentation describes how to install the connector: <link>
- [ X] Documentation describes how to contact maintainer: <link>

Thank you!

**Comment by bastiankoerber** [comment]
added to the awesome list
